### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by georgymh** [jiahuei/COMIC-Compact-Image-Captioning-with-Attention#1]
Thanks so much for releasing the code to your paper! I was wondering if you were planning to release any pre-trained weights any time soon? That would be amazing if you will.

**Comment by jiahuei** [comment]
Hi there, the pretrained weights are now provided for COMIC-256 models trained using the updated training scheme. Hope it helps.

**Comment by georgymh** [comment]
I checked and they do reproduce the paper's results for MS-COCO. Thank you!

Could you also release the pre-trained weights for the InstaPIC-1.1M dataset (and instructions) whenever you have the chance?

**Comment by jiahuei** [comment]
The README file has been updated for clearer instructions on how to train on InstaPIC. The Insta weights might take some time as I am currently working on another project. 

The pretrained models are also moved into a separate repo. Details in README.

Thanks and you are welcome!
